[package]
name = "jangada-core"
version.workspace = true
edition.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
serde = { workspace = true, optional = true }
rand.workspace = true
tracing.workspace = true
